# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netbird < Formula
  desc "Netbird project."
  homepage "https://netbird.io/"
  version "0.64.5-axt"
  license "BSD3"

  on_macos do
    on_intel do
      url "https://github.com/axtesys-GmbH/netbird/releases/download/v0.64.5-axt/netbird_0.64.5-axt_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "1663033407fc234d391b263c2b464abfadf1c3f1346ceb823521e18a47716fa8"

      def install
        bin.install "netbird"
      end
    end
    on_arm do
      url "https://github.com/axtesys-GmbH/netbird/releases/download/v0.64.5-axt/netbird_0.64.5-axt_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "23066654f590a122440f7e5aba74a0a78a42a396ead1fd99fa3441e9db219954"

      def install
        bin.install "netbird"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/axtesys-GmbH/netbird/releases/download/v0.64.5-axt/netbird_0.64.5-axt_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "e6f0a08fee0eb60c3a7e3f6166719bf4d97713906dc25ac590e7db35ea6b8500"

        def install
          bin.install "netbird"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/axtesys-GmbH/netbird/releases/download/v0.64.5-axt/netbird_0.64.5-axt_linux_armv6.tar.gz", using: CurlDownloadStrategy
        sha256 "6aa6dbe9e36f9d7c92bf6b6d4c04c0fae9cf101c266ba24bb01c1437b6f00859"

        def install
          bin.install "netbird"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/axtesys-GmbH/netbird/releases/download/v0.64.5-axt/netbird_0.64.5-axt_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "b0c865187f2926b24534d7e9533be44aaf24cfc373740b08244d1a8ee84cc91b"

        def install
          bin.install "netbird"
        end
      end
    end
  end

  test do
    system "#{bin}/netbird version"
  end
end
