# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netbird < Formula
  desc "Netbird project."
  homepage "https://netbird.io/"
  version "0.73.2-axt"
  license "BSD3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/axtesys/netbird/releases/download/v0.73.2-axt/netbird_0.73.2-axt_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "50b8a6ad653da80079072c6877e256aa55033f3ec6b990cf630974ebfb32f45a"

      define_method(:install) do
        bin.install "netbird"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/axtesys/netbird/releases/download/v0.73.2-axt/netbird_0.73.2-axt_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7e1844f4a5433d35ffdbe2b824d67fb496890dc1d18cf0baa75f4a724bc9e13d"

      define_method(:install) do
        bin.install "netbird"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/axtesys/netbird/releases/download/v0.73.2-axt/netbird_0.73.2-axt_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "29d4b844912acdc8fb26f284e1ebcaf7edb66cbe98fd3a6e0817d1afb05a4362"
      define_method(:install) do
        bin.install "netbird"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/axtesys/netbird/releases/download/v0.73.2-axt/netbird_0.73.2-axt_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "8cbacb35bc561f9bdbf90d5f6b3921b657f3ff8308330e436c3ba64b9c3522b2"
      define_method(:install) do
        bin.install "netbird"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axtesys/netbird/releases/download/v0.73.2-axt/netbird_0.73.2-axt_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e4439d3c8543955d123cf22560d1f47c37feb3943029f243422db5e2ad8c59e5"
      define_method(:install) do
        bin.install "netbird"
      end
    end
  end

  test do
    system "#{bin}/netbird version"
  end
end
